airootfs/usr/share/vx-img/flash-image.sh

This PR streamlines the user flow, relying on smart defaults. If everything happens as default (there is only one image, it has the correct file name, and only one disk to flash), the user only has to press enter one time to flash an image. Straying from the default case presents the users with progressively more and more prompts depending on how deviant their case is. 
Note @carolinemodic: I used disk labels to autodetect the Ventoy data partition, so I don't think we actually need to create a different boot entry for the happy path.

Working on QoL improvements

---

airootfs/usr/share/vx-img/flash-image.sh

If the filename has a decimal point in the file size, pv will choke on it. Strip off the decimal point and everything after so that doesn't happen.

fixing decimal point file size bug

---

airootfs/usr/share/vx-img/flash-image.sh
airootfs/usr/share/vx-img/scrape-image.sh

* scraped images will now use underscores as separators in the timestamp
* images that are automatically detected may now use colons, spaces, or
underscores in their timestamps
Closes #40.

Altering naming conventions

---

efiboot/loader/loader.conf

Fixes the systemd-boot menu timeout being too short (issue #49). 
N/A

Resetting the systemd-boot timeout to 3s

---

airootfs/usr/share/vx-img/flash-image.sh
packages.x86_64

Currently detects if the system that's being flash has an existing vx install, tars up /vx/config, flashes, then untars and writes back /vx/config.

Copies /vx/config from one install to the next

---

airootfs/usr/share/vx-img/flash-image.sh

Makes sure that the correct boot entry is setup when flashing on a Surface Go so that Secure Boot works. 
N/A
Manually tested.

Fixing Surface Go boot entry

---

airootfs/usr/share/vx-img/flash-image.sh

Closes #68. 
If the string "vxdev" appears in the filename of the image to flash (case insensitive), sets up a normal grub entry instead of an EFI entry.

Fixing VxDev boot entry

---

roles/vx-iso/tasks/remount_usb.yaml
roles/vx-iso/tasks/vx-img.yaml
scripts/copy-image.sh
scripts/install-ansible.sh

This PR is primarily for adding convenience scripts to simplify copying an image file to USB. It also adds a `sync` call after copying to the USB to ensure the image is completely written to the USB.

helper scripts for SLI and ensure the USB syncs after copy

---

airootfs/etc/localtime

Explicitly sets the timezone to UTC to fix an interactive prompt on each menu selection.

set TZ to UTC to avoid interactive prompt on any menu action

---

airootfs/usr/share/vx-img/flash-image.sh

Create more useful boot labels based on the image name and date. This will also assist with future functionality to remove older boot entries.

make boot labels more human friendly

---

README.md
playbooks/flash_vx-iso.yaml
roles/vx-iso/tasks/main.yaml
roles/vx-iso/tasks/partition_vx-img.yaml
roles/vx-iso/tasks/remount_usb.yaml
roles/vx-iso/tasks/usb_mgmt.yaml
roles/vx-iso/tasks/vx-img.yaml
roles/vx-iso/tasks/vx-iso.yaml
scripts/copy-image.sh
scripts/create-install-drive.sh

This PR is focused on making the creation of both install and image USB drives simpler, more flexible, and more consistent. Rather than requiring the explicit use of `ansible-playbook` commands and associated environment and syntax, simple script wrappers are now provided (along with documentation updates). 
Of note:
- the use of sleep commands when managing usb drives has been significantly reduced. Instead, Ansible's `wait_for` is used to verify the state of usb drives before performing related operations
- we no longer force re-partitioning of a usb drive. If the drive matches our expected partition scheme, we simply copy files to the drive. This enables the use of usb drives with multiple images. If the drive does not match our expected scheme, we still perform a full re-partition.
- …

Usability and functional improvements for creating install and image usb drives

---

roles/vx-iso/tasks/vx-img.yaml

EXT4 filesystems are automounted with permissions based on the state of the drive at creation/modification. This can result in requiring sudo privileges to modify contents of the USB drive. This change fixes the issue by making the directory contents accessible to everyone since we can't know the users/uids of all possible environments ahead of time.

workaround for the way ext4 automount permissions are applied

---

live-build/includes.chroot/usr/local/bin/flash-image.sh
live-build/vxiso.list.chroot

This PR removes the manual prompt asking for final size of the image being installed. Instead, it extracts the necessary boot header information and calculates the size from that info. If the size can't be determined, we default to 64G.

Automatically detect size of image being installed

---

live-build/includes.chroot/usr/local/bin/flash-image.sh

This PR is our initial implementation of persisting an existing VotingWorks application configuration when upgrading the installed version of the application.
We have identified 4 conditions that must all be met to automatically persist a system's configuration across installs. If any of these fail, we fall back to our normal configuration wizard.
The criteria:
* Secure Boot states must be the same
* Machine types must be the same
* QA states must be the same
* Certificates must be the same
Prior to flashing an image, we inspect the above criteria for the currently installed image and store it in memory/variables, along with creating a tarball of the config to persist.
After flashing the new image, we inspect the same criteria for the newly installed image and compare to the previously …

Initial /vx/config persistence

---

live-build/includes.chroot/usr/local/bin/flash-image.sh

This PR adds several improvements to the vx-iso image installation process.
- If only one image is present in the `Data` directory, it is automatically selected for installation. (You can still cancel the install before it automatically proceeds.)
- Obsolete boot entries from previous installs are automatically deleted. This results in only one VotingWorks boot entry, making it easier to troubleshoot boot issues, and prevents an incorrect boot entry from being used. 
- Adds a more generalized approach to detecting possible USB boot entries across different hardware/bios implementations. This should result in valid USB drives booting automatically, with the exception of bios implementations that do not respect `efibootmgr` boot order changes related to USB drives.
I've also started moving …

Improvements: boot order management, image selection

---

live-build/includes.chroot/usr/local/bin/flash-image.sh

While we prefer to exclude EMMC drives from production use, we need to include them when they are the only option. This PR defaults to not selecting an EMMC drive, but if no other drives are found, it checks again with the EMMC restriction removed.

allow mmc drive when it's the only option

---

live-build/includes.chroot/usr/local/bin/flash-image.sh

During v4.0.2 imaging, we discovered an edge-case related to config persistence. In the event that an image was successfully installed to disk, but it then failed to proceed through config persistence or the config wizard, it can be left in a state that will also result in subsequent installs not going through the config wizard. When this happens, manual intervention is necessary to force the config wizard flow. This PR adds a check to config persistence related to the machine ID. If it's still the default of `0000`, that's good signal that something on the current install is incorrect, so we should not persist the configuration during installation of the newest image.

add machine id to config persistence check

---

live-build/includes.chroot/usr/local/bin/flash-image.sh

To be compliant with FIPS, the `openssl fipsinstall` command must be run on each system. This adds a flag file when config persistence takes place since the basic config wizard (where we originally perform the fipsinstall) will be skipped.

Force fipsinstall on first boot when config is persisted

---

live-build/includes.chroot/etc/initramfs-tools/scripts/live-premount/dmverity-root
live-build/initialize-usb.sh
live-build/install-vx-iso-to-usb.sh

This PR addresses newer USB drives that can show up as not-removable (even though they are) via normal methods of determining removable status. Rather than using the `removable` value found via `/sys/block/<device>/removable` or the `RM` flag with the `lsblk` command, we're now checking the device transport type (`TRAN`) value to identify a usb device.

Handle newer USB drives that do not adhere to removable device standards

---

live-build/initialize-usb.sh
live-build/install-vx-iso-to-usb.sh

The `Data` partition is an `ext4` filesystem, and permissions are not inherited well across different Linux systems. This PR sets the permissions on that partition to `777` so that sudo is not required when copying files to the partition. This set of permissions is set during USB initialization and installing vx-iso to a USB. 
This closes https://github.com/votingworks/vxsuite/issues/6432

Make the Data partition writeable without requiring sudo privileges
